### ISSUE TITLE
Wrong file format when installing with pip3

### ISSUE THREAD

**Issue by Freedzone** [0xInfection/XSRFProbe#38]
#### Describe the bug
Cannot start the tool after installing with pip3: `/usr/bin/env: ‘python3\r’: No such file or directory`. I have installed pip through the get-pip.py, not repository.
For some reason `/usr/local/bin/xsrfprobe` is formatted as Windows file.

#### Command You Used
xsrfprobe

#### Environment:
- __OS__: [Kali Rolling 2019.4]
- __Python version__: [v3.7.5]

#### Some Questions

- [x] I am using the latest version of XSFRProbe.
- [x] I installed the dependecies using `pip3` instead of `pip`.
- [x] I have read the documentation before submitting this issue.
- [x] I have checked the other issues to see if someone reported this before.

**Comment by 0xInfection** [comment]
Hi @Freedzone, thank you for reporting this issue. 

I have identifed that it is the issue with line endings. I will look into this properly. 

Meanwhile please use `git` for directly cloning this toolkit. Git will automatically handle line endings and convert them to Linux based line endings so that you can use this tool. :)

**Comment by 0xInfection** [comment]
Fixed in fe580c3. Version 2.3 is released. :)
